version: "3.9"  

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simba-website-new
    ports:
      - "4028:80" 
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
